[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nnpiv"
authors = [{name = "isaac", email = "isaac@harvrad"}]
dynamic = ["version", "description"]
